#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t molssicheminfo \
                         -C "start_jupyter -t -T @tool molssicheminfo.ipynb" \
                         -r none -w headless arguments \
                         -u anaconda-7
